language: java

sudo: false
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk11

env:
  global:
    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

notifications:
  email: false

install: false

before_script:
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

script:
  - mvn clean verify  -B -V -Pfull
# Use these for maven wrapper - git strips the wrapper jar file so we have to force its download during the build.
#  - mvn -N io.takari:maven:wrapper
#  - ./mvnw install -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn


